### ISSUE TITLE
Typo in the GitHub description

### ISSUE THREAD

**Issue by chmac** [Ondolin/gotify-matrix-bot#17]
On the "code" or "homepage", there's a project name & description (top right on desktop browsers). The description has the word chart where I think it should be chat.

Otherwise, thanks for this software, it's exactly the missing piece that I'd need to have gotify notifications plumbed to my iOS devices on my own self hosted setup! 🧡

**Comment by Ondolin** [comment]
Thank you, I fixed the mistake :D

I am glad that my software can help you. If you have any trouble with it, just open another issue and I'll try to fix it.
