### ISSUE TITLE
Code 400 Unrecognized request

### ISSUE THREAD

**Issue by Avi0n** [Ondolin/gotify-matrix-bot#2]
Set up via docker but got this message when trying to send a notification to a matrix room. The bot is a member of the room and the room is unencrypted.

```
2021/07/31 22:43:00 Send new unencrypted message to matrix server &{https://matrix.homeserver.tld botUsername botToken  0xc00061d080} . Message content:  my message
2021/07/31 22:43:00 Could not send the message to the matrix server! contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 85 78 82 69 67 79 71 78 73 90 69 68 34 44 34 101 114 114 111 114 34 58 34 85 110 114 101 99 111 103 110 105 122 101 100 32 114 101 113 117 101 115 116 34 125] msg=Failed to PUT JSON to /_matrix/client/r0/rooms/send/m.room.message/go1627771380117393306 code=400 wrapped=M_UNRECOGNIZED: Unrecognized request
```

**Comment by Ondolin** [comment]
Do you use a password or an auth token?

*It´s_ a little bit unintuitive, but currently you have to use a token for unencrypted messages and a password for encrypted ones. Till now I had no time to fix this, but I´ll do this in the near future.*

**Comment by Avi0n** [comment]
I have both password and token filled in config.yaml.

**Comment by Ondolin** [comment]
Do you use the latest version for the gotify server (2.0.23)?

**Comment by Avi0n** [comment]
I fixed this issue by enclosing the auth token with quotes. Maybe this could be documented for those unfamiliar with how yaml files work?

**Comment by Ondolin** [comment]
OK. I'll update my README within the near future and add a better error message for this kind of problem.
