### ISSUE TITLE
[Feature Request] Markdown support

### ISSUE THREAD

**Issue by Avi0n** [Ondolin/gotify-matrix-bot#3]
I would like the bot to be able to send markdown formatted messages from gotify to matrix.

**Comment by Ondolin** [comment]
Markdown formatting for messages is now (since version 1.2.0) available. Just pull the new docker image and thinks should work

**Comment by Avi0n** [comment]
@Ondolin I think you accidentally left your bot's name and token in unecrypted.go and encrypted.go

**Comment by Ondolin** [comment]
Oh, crap. You are right. That's why you don't do thinks in the evening. Fixed it in version 1.2.1
