### ISSUE TITLE
Could not load config.yaml: line 5: did not find expected key

### ISSUE THREAD

**Issue by MrCustomizer** [Ondolin/gotify-matrix-bot#4]
I've tried starting the docker container with a config.yaml placed in a directory which is mounted in the path /data of the container. The location seems to be correct, although the documentation sadly doesn't seem to mention, that this file should be placed in the data directory.
When starting the container it always fails with the message `Could not load config.yaml: line 5: did not find expected key`.
My config file looks like this:
```
gotify:
  URL: "REDACTED"
  apiToken: "REDACTED"
  pollTime: "*/10 * * * * *"
matrix:
  homeserverURL: "REDACTED"
  username: "REDACTED"
  password: "REDACTED"
  token: ""
  roomID: "REDACTED"
  encrypted: true
debug: false
```

Is this a bug or am I doing something wrong?

**Comment by Ondolin** [comment]
As far as I can tell the code is working perfectly fine.  
Your container can not read from the config file. This could have several reasons.  
1. have you checked your docker volume was mounted correctly? What docker command do you use to start the container?
2. make sure your file is named correctly (`config.yaml`)

**Comment by MrCustomizer** [comment]
It wasn't a permission problem, there was a " in my Matrix user's password. This caused the error. It's solved now. Sorry for the issue.
