### ISSUE TITLE
Need to generate a new token every 50 messages?

### ISSUE THREAD

**Issue by nothing2obvi** [Ondolin/gotify-matrix-bot#8]
Maybe I'm doing this wrong, but I believe my Gotify notifications stop showing up in my Matrix chatroom after 50 messages, then I have to generate a new token. Is there any way to auto-renew the token or get around this issue? I use an iMessage-bridge for Matrix as well in combination with the [shared-secret-authenticator](https://github.com/devture/matrix-synapse-shared-secret-auth)....Is this something that could work with this gotify-matrix-bot? Thanks!

**Comment by Ondolin** [comment]
Access tokens typically do not expire. So this should not be a problem of this project. 
But nevertheless some questions:

Do you use synapse as a homeserver?
Do you have a "dedicated bot account"? Or do you use your default account?
Have you generated the access token using [this](https://github.com/Ondolin/gotify-matrix-bot/wiki/Config-file#matrixtoken) command?
Your log files might be useful for further debugging as well. (This project has no real log files. The log is the shell output.)
Using `debug: true` might reveal some further information.

I don't have an iMessage-bridge, but I have a whatsapp and telegram bridge. But all of them should not cause any trouble.
I don't know what your shared-secret-authenticator does. It might cause some problems. If that is the case, the log files should contain some errors.

**Comment by nothing2obvi** [comment]
Hey thanks for the quick response. Hmm, interesting. Yeah for some odd reason after a certain amount of messages they just stop appearing in the chat room unless I use the command you referenced to get a new token and place it in the "config.yaml" file. Yes, I'm synapse as a homeserver and a dedicated account for the bot. I'll look into it a little further and will report what I can find.

**Comment by Ondolin** [comment]
Is there some message in the logs?
